Correct term 44 end date
tmtmtmtm/australia-openaustralia pull request #4
Opened 2016-09-22 14:38 UTC by ondenman

The end date for term 44 was incorrect, causing problems with the data.

2016-09-22 14:48 UTC, tmtmtmtm requested changes
You really need to include a source for this information in the commit message.

However, maintaining this list in multiple places is also providing problematic, so I'd say this should be entirely replaced with looking it up using everypolitician-ruby:

`EveryPolitician::Index.new.country('Australia').legislature('Representatives').legislative_periods`

2016-09-22 15:38 UTC, ondenman commented
Term dates now read from manual file in ep-data repo.

2016-09-23 06:53 UTC, tmtmtmtm commented on Gemfile
> +gem 'everypolitician'
I don't think you need to include this any more, do you?

2016-09-23 06:54 UTC, tmtmtmtm requested changes

2016-09-23 10:39 UTC, tmtmtmtm requested changes
You've removed the Gemfile, but not the Gemfile.lock

2016-09-23 13:43 UTC, tmtmtmtm requested changes
You still have what appear to be needless changes to `Gemfile.lock`

Rather than adding https://github.com/everypolitician-scrapers/australia-openaustralia/pull/4/commits/aafb75a43bdf96a4ba1e4e61be8f06550b064631 to revert https://github.com/everypolitician-scrapers/australia-openaustralia/pull/4/commits/c722a04d9cd683f11679d304f2954c128cf86c7d, I'd suggest you simply drop both commits.

2016-09-23 13:55 UTC, ondenman commented
@tmtmtmtm I've rebased and removed both of the gemfile commits.

2016-09-23 14:15 UTC, tmtmtmtm approved these changes

2016-09-23 14:15 UTC, merged